image: microsoft/dotnet:latest

stages:
  - build
  - grade

before_script:
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build"
  artifacts:
    paths:
      - "*/bin/*/*/*"

grade:
  stage: grade
  script:
    - "dotnet Zarwin.Shared.Grader/bin/Debug/netcoreapp2.0/Zarwin.Shared.Grader.dll $CI_COMMIT_REF_NAME"
  artifacts:
    paths:
      - "grade.json"
      - "*.svg"
